m4_minecraft_homepage:
    path:     /
    defaults: { _controller: M4MinecraftBundle:Default:index }

m4_minecraft_create:
    path:     /create
    defaults: { _controller: M4MinecraftBundle:Default:create }


m4_minecraft_show:
    path:     /show
    defaults: { _controller: M4MinecraftBundle:Default:show }


m4_minecraft_new:
    path:     /new
    defaults: { _controller: M4MinecraftBundle:Default:new }
