m4_minecraft_homepage:
    path:     /
    defaults: { _controller: M4MinecraftBundle:Default:index }

m4_minecraft_add:
    path:     /add
    defaults: { _controller: M4MinecraftBundle:Default:add }
