m4_minecraft_homepage:
    path:     /
    defaults: { _controller: M4MinecraftBundle:Default:index }

m4_minecraft_add:
    path:     /add
    defaults: { _controller: M4MinecraftBundle:Default:add }

m4_minecraft_server:
    path:    /server/{id}
    defaults: { _controller: M4MinecraftBundle:Default:server }

m4_minecraft_donut:
    path:    /donut
    defaults: { _controller: M4MinecraftBundle:Default:donut }